# Generated by Django 4.1.1 on 2022-09-29 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_challange_player_delete_duel_challange_from_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challange',
            name='from_player',
            field=models.ForeignKey(on_delete=models.SET(games.models.get_sentinel_user), related_name='my_challenges', to='games.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
    ]
