# Generated by Django 4.1.1 on 2022-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_player_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challange',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_game', 'In game'), ('done', 'Done')], default='waiting', max_length=25),
        ),
    ]
