# Generated by Django 4.1.1 on 2022-10-11 16:46

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_challange_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draw', models.BooleanField(default=False)),
                ('loser', models.ForeignKey(on_delete=models.SET(games.models.get_sentinel_user), related_name='loser', to='games.player')),
                ('winner', models.ForeignKey(on_delete=models.SET(games.models.get_sentinel_user), related_name='winner', to='games.player')),
            ],
        ),
        migrations.AddField(
            model_name='challange',
            name='game',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='games.game'),
        ),
    ]
