# Generated by Django 4.1.1 on 2022-10-11 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_challange_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challange',
            name='game',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', to='games.game'),
        ),
    ]
