# Generated by Django 4.1.1 on 2022-10-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_remove_challange_from_player_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
